### ISSUE TITLE
No option for defaultValue

### ISSUE THREAD

**Issue by seaophiel** [AdelRedaa97/react-native-select-dropdown#5]
Hi, thanks for this great repo. I need a prop like "defaultValueByIndex" to allows me to pass a object instead of a index. I created the following code that allow me to do that (this is working in my project):

```javascript
useEffect(() => {
      if (defaultValue && data) {
        let isValid = false;
        data.map((item, index) => {
          if (defaultValue == item) {
            isValid = true;
          }
        });

        if (isValid) {
          setSelectedItem(defaultValue);
        }
      }
    }, [defaultValue]);
```

**Comment by AdelRedaa97** [comment]
Hello Seaophiel, thanks for your interest, default value is added now to v1.0.7 ,  I would like to tell you that Object comparison in javascript using == is not efficient because it returns true only if two objects are exact the same.

`
const objOne = {  number: 1,  name: 'abc' };
const objTwo = {  number: 1,  name: 'abc' };

objOne == objTwo // return true

const objOne = {  number: 1,  name: 'abc' };
const objTwo = {  name: 'abc',   number: 1 };

objOne == objTwo // returns false

`
So i used Lodash `_.isEqual(objOne, objTwo)`  for comparison it works good.

**Comment by seaophiel** [comment]
Thanks AdelRedaa97, I will update it now !
