### ISSUE TITLE
Keyboard over drobox when searchable

### ISSUE THREAD

**Issue by kkkasio** [AdelRedaa97/react-native-select-dropdown#81]
I have several "dropbox" on my screen, when selected with the search property, the keyboard is rendered over this one.
Has anyone had the same problem?

Evidences:
![image](https://user-images.githubusercontent.com/19254402/177843762-83236e16-cfac-4520-9b0f-d4ba6df1eb14.png)

![image](https://user-images.githubusercontent.com/19254402/177843235-55f4a521-ce34-480e-9680-fa44892ac9b5.png)

**Comment by AdelRedaa97** [comment]
When the keyboard is displayed over the dropdown, it's shifted to the top to appear at least the search input and two options under it.

**Comment by kkkasio** [comment]
> Quando o teclado é exibido sobre o menu suspenso, ele é deslocado para o topo para aparecer pelo menos a entrada de pesquisa e duas opções abaixo dela.

Thanks for your response. So this is the expected behavior?

**Comment by AdelRedaa97** [comment]
Yes, exactly

**Comment by mastersam92** [comment]
But.. it seems like some crap or bug
Seriously, why block with search string and suggestions have some margin when keyboard is opened  and how disable this

Keyboard on down section of screen. Why some margins appearing on top/center and why it's expected behavior ?
Why it's crap - is expected behavior, could you explain ?
